# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 15:43
from __future__ import unicode_literals

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_auto_20161021_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(upload_to=''),
        ),
    ]
